channels:
  - conda-forge
  - bioconda
dependencies:
  - r-base=3.6
  - r-sp
  - r-raster
  - r-rgdal
  - r-ggplot2
  - r-agricolae
  - r-reshape2
  - r-devtools
  - r-lme4
  - r-plyr
  - r-desctools
  - r-doparallel
  - r-foreach
  - r-maptools
  - r-igraph
  - r-ggrepel
  - r-spatialeco
  - r-attempt
  - r-config
  - bioconductor-ebimage
